apiVersion: elasticsearch.elasticstack.k8s.elastic.co/v1alpha1
kind: SecurityRole
metadata:
  annotations:
    meta.upbound.io/example-id: elasticsearch/v1alpha1/securityrole
  labels:
    testing.upbound.io/example-name: role
  name: role
spec:
  forProvider:
    applications:
    - application: myapp
      privileges:
      - admin
      - read
      resources:
      - '*'
    cluster:
    - all
    indices:
    - names:
      - index1
      - index2
      privileges:
      - all
    metadata: |-
      ${jsonencode({
          version = 1
        })}
    name: testrole
    runAs:
    - other_user
