apiVersion: elasticsearch.elasticstack.k8s.elastic.co/v1alpha1
kind: SnapshotLifecycle
metadata:
  annotations:
    meta.upbound.io/example-id: elasticsearch/v1alpha1/snapshotlifecycle
  labels:
    testing.upbound.io/example-name: slm_policy
  name: slm-policy
spec:
  forProvider:
    expireAfter: 30d
    ignoreUnavailable: false
    includeGlobalState: false
    indices:
    - data-*
    - important
    maxCount: 50
    minCount: 5
    name: my_slm_policy
    repository: my_url_repo
    schedule: 0 30 1 * * ?
    snapshotName: <daily-snap-{now/d}>

---

apiVersion: elasticsearch.elasticstack.k8s.elastic.co/v1alpha1
kind: SnapshotRepository
metadata:
  annotations:
    meta.upbound.io/example-id: elasticsearch/v1alpha1/snapshotlifecycle
  labels:
    testing.upbound.io/example-name: repo
  name: repo
spec:
  forProvider:
    fs:
    - compress: true
      location: /tmp/snapshots
      maxRestoreBytesPerSec: 20mb
    name: my_snap_repo
