apiVersion: elasticsearch.elasticstack.k8s.elastic.co/v1alpha1
kind: SnapshotRepository
metadata:
  annotations:
    meta.upbound.io/example-id: elasticsearch/v1alpha1/snapshotrepository
  labels:
    testing.upbound.io/example-name: my_url_repo
  name: my-url-repo
spec:
  forProvider:
    name: my_url_repo
    url:
    - url: https://example.com/repo
